
# dir_server = '/data/maheen'
# str_replace = ['..','/data/maheen/nn_net']

# dir_server = '/data/maheen-data'
# str_replace = ['..','/data/maheen-data/nn_net']

# vision6
dir_server = '/disk2/maheen_data'
str_replace = ['..','/disk2/maheen_data/nn_net']


class_names_ucf = ['BaseballPitch', 'BasketballDunk', 'Billiards', 'CleanAndJerk', 'CliffDiving', 'CricketBowling', 'CricketShot', 'Diving', 'FrisbeeCatch', 'GolfSwing', 'HammerThrow', 'HighJump', 'JavelinThrow', 'LongJump', 'PoleVault', 'Shotput', 'SoccerPenalty', 'TennisSwing', 'ThrowDiscus', 'VolleyballSpiking']
class_names_ucf.sort()

class_names = class_names_ucf[:]

class_names_activitynet = ['Archery',
'Ballet',
'Bathing dog',
'Belly dance',
'Breakdancing',
'Brushing hair',
'Brushing teeth',
'Bungee jumping',
'Cheerleading',
'Chopping wood',
'Clean and jerk',
'Cleaning shoes',
'Cleaning windows',
'Cricket',
'Cumbia',
'Discus throw',
'Dodgeball',
'Doing karate',
'Doing kickboxing',
'Doing motocross',
'Doing nails',
'Doing step aerobics',
'Drinking beer',
'Drinking coffee',
'Fixing bicycle',
'Getting a haircut',
'Getting a piercing',
'Getting a tattoo',
'Grooming horse',
'Hammer throw',
'Hand washing clothes',
'High jump',
'Hopscotch',
'Horseback riding',
'Ironing clothes',
'Javelin throw',
'Kayaking',
'Layup drill in basketball',
'Long jump',
'Making a sandwich',
'Mixing drinks',
'Mowing the lawn',
'Paintball',
'Painting',
'Ping-pong',
'Plataform diving',
'Playing accordion',
'Playing badminton',
'Playing bagpipes',
'Playing field hockey',
'Playing flauta',
'Playing guitarra',
'Playing harmonica',
'Playing kickball',
'Playing lacrosse',
'Playing piano',
'Playing polo',
'Playing racquetball',
'Playing saxophone',
'Playing squash',
'Playing violin',
'Playing volleyball',
'Playing water polo',
'Pole vault',
'Polishing forniture',
'Polishing shoes',
'Preparing pasta',
'Preparing salad',
'Putting on makeup',
'Removing curlers',
'Rock climbing',
'Sailing',
'Shaving',
'Shaving legs',
'Shot put',
'Shoveling snow',
'Skateboarding',
'Smoking a cigarette',
'Smoking hookah',
'Snatch',
'Spinning',
'Springboard diving',
'Starting a campfire',
'Tai chi',
'Tango',
'Tennis serve with ball bouncing',
'Triple jump',
'Tumbling',
'Using parallel bars',
'Using the balance beam',
'Using the pommel horse',
'Using uneven bars',
'Vacuuming floor',
'Walking the dog',
'Washing dishes',
'Washing face',
'Washing hands',
'Windsurfing',
'Wrapping presents',
'Zumba']

class_names_activitynet_select = ['Archery',
'Breakdancing',
'Brushing teeth',
'Bungee jumping',
'Cheerleading',
'Chopping wood',
'Cleaning shoes',
'Cleaning windows',
'Cricket',
'Discus throw',
'Doing nails',
'Drinking beer',
'Drinking coffee',
'Fixing bicycle',
'Getting a haircut',
'Getting a piercing',
'Getting a tattoo',
'Hammer throw',
'Hand washing clothes',
'High jump',
'Horseback riding',
'Ironing clothes',
'Javelin throw',
'Kayaking',
'Layup drill in basketball',
'Long jump',
'Making a sandwich',
'Paintball',
'Painting',
'Ping-pong',
'Plataform diving',
'Playing accordion',
'Playing field hockey',
'Playing flauta',
'Playing harmonica',
'Playing polo',
'Playing saxophone',
'Playing squash',
'Playing violin',
'Playing volleyball',
'Pole vault',
'Polishing forniture',
'Polishing shoes',
'Preparing pasta',
'Putting on makeup',
'Removing curlers',
'Rock climbing',
'Sailing',
'Shaving',
'Shaving legs',
'Shot put',
'Shoveling snow',
'Skateboarding',
'Smoking a cigarette',
'Smoking hookah',
'Snatch',
'Spinning',
'Springboard diving',
'Tennis serve with ball bouncing',
'Triple jump',
'Tumbling',
'Vacuuming floor',
'Walking the dog',
'Washing face',
'Washing hands']